#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Dec 04 20:55:50 PST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim mmu_tb_behav -key {Behavioral:sim_1:Functional:mmu_tb} -tclbatch mmu_tb.tcl -log simulate.log"
xsim mmu_tb_behav -key {Behavioral:sim_1:Functional:mmu_tb} -tclbatch mmu_tb.tcl -log simulate.log

